version: '3.0'
services:
  fragment:
    volumes:
      - ./tests/ssl/az.pem:/etc/ssl/certs/az.pem
  manifest:
    volumes:
      - ./tests/ssl/az.pem:/etc/ssl/certs/az.pem
  auth:
    image: lambdaville/no-factor-auth:v0.1.0
    environment:
      - TOKEN_ENDPOINT_ISSUER=https://sts.windows.net/
      - TOKEN_ENDPOINT_AUDIENCE=https://storage.azure.com
      - TOKEN_ENDPOINT_SUBJECT=https://storage.azure.com

  az:
    image: mcr.microsoft.com/azure-storage/azurite:3.8.0
    command: azurite-blob --blobHost 0.0.0.0 --oauth basic --loose --cert /tests/ssl/az.pem --key /tests/ssl/key.pem
    volumes:
      - ./tests/ssl:/tests/ssl
    ports:
      - 10000:10000

  rapi:
    image: oneseismic.azurecr.io/api:${VERSION:-latest}
    depends_on:
      - auth
      - az
    environment:
      - AUTHSERVER=http://auth:8089/common
      - AUDIENCE="MY_AUDIENCE"
      - AZURE_STORAGE_URL=https://az:10000/devstoreaccount1
      - HOST_ADDR=0.0.0.0:8080
      - AZURE_STORAGE_ACCOUNT
      - CLIENT_ID
      - CLIENT_SECRET
      - LOG_LEVEL
      - ZMQ_REP_ADDR=tcp://*:6144
      - ZMQ_REQ_ADDR=tcp://*:6143
      - ZMQ_FAILURE_ADDR=tcp://*:6140
      - RUST_LOG=info,rapi=trace

    volumes:
      - ./tests/ssl/az.pem:/etc/ssl/certs/az.pem
  test:
    build:
      context: .
      dockerfile: tests/integration/Dockerfile
    depends_on:
      - api
      - az
      - auth
    environment:
      - AUDIENCE="MY_AUDIENCE"
      - API_ADDR=http://api:8080
      - AUTHSERVER=http://auth:8089/common
      - AZURE_STORAGE_URL=https://az:10000/devstoreaccount1
