name: API
on:
  push:
    branches:
    - gha
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install zmq and protobuf
      run: sudo apt-get update && sudo apt-get install -y libzmq5-dev protobuf-compiler

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Download dependencies
      run: go mod download
      working-directory: ./api

    - name: Generate protobuf code
      run: go generate
      working-directory: ./api

    - name: Build
      run: go build
      working-directory: ./api

    - name: Test
      run: go test -race ./...
      working-directory: ./api
